name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven with jdk 8
        run: mvn -ntp clean compile test-compile --file pom.xml
      - name: Run tests with jdk 8
        run: mvn -ntp -fae test --file pom.xml
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven with jdk 17
        run: mvn -ntp clean compile test-compile --file pom.xml
      - name: Run tests with jdk 17
        run: mvn -fae -ntp test --file pom.xml
